[tool.black]
line-length = 90
target-version = ['py312']
include = '\.pyi?$'

[tool.isort]
profile = "django"
combine_as_imports = true
include_trailing_comma = true
line_length = 90
multi_line_output = 3
known_first_party = ["config"]
